---
title: "Results Tables"
output: pdf_document
---

```{r,  echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, message = FALSE)

options(knitr.kable.NA = "0",
        tinytex.verbose = TRUE)

library(ggplot2)
library(dplyr)
library(data.table)
library(lubridate)
library(kableExtra)
library(stringr)
library(fs)
library(parkinsonstandemcycling)
```

```{r}
demographicsTable |>
  dplyr::select(var, meansd) |>
  kableExtra::kable(
    booktabs = T,
    caption = "Participant Demographics and Parkinson’s Disease Patient Clinical Measures",
    col.names = c("", "Mean (Std.Dev.)"),
    full_width = F
  )  |>
  kableExtra::pack_rows("Care Partner", 1, 4) |>
  kableExtra::pack_rows("Persons with Parkinson's Disease", 5, 12)
```

```{r}
scoreInterpretationTable |>
  kableExtra::kable(
    booktabs = T,
    caption = "Score Interpretation of Psychometric Instruments Administered",
    col.names = c('Instrument',
                  'Score Interpretation',
                  'Pre-test',
                  'Post-test',
                  'Pre-test',
                  'Post-test'))|>
  kableExtra::add_header_above(
    header = c(' '=2, 'CP' = 2, 'PwPD' = 2))|>
  kableExtra::collapse_rows(columns = 1)
```

```{r}
pwpTtestTable |>
  dplyr::filter(Instrument %in% c(
    "UPDRS", "FGATotal", "TenMGS", 'PDQ39', 'PROMIS', 'GD', 'GAD7','MOCA','BRS', 'RDA', 'HRV'
  ))|>
  dplyr::filter(!(Instrument == "RDA" & dimension %in% c(
    'Decision Making','Values','Affection','Stability','Conflict',
            'Activities','Discussion', 'Total Score RDAS'
  ) ))|>
  dplyr::mutate(
    Instrument = factor(Instrument, levels = c(
    "UPDRS", "FGATotal", "TenMGS", 'PDQ39', 'PROMIS', 'GD', 'GAD7','MOCA','BRS', 'RDA', 'HRV'
  ),
  labels = c("UPDRS-III", "FGA", "10-m Gait Speed", 'PDQ-39', 'PROMIS-29','GDS-SF','GAD-7','MoCA', 'BRS', 'RDAS', 'HRV')),
  Dimension = factor(dimension, levels = c(
    '',
    'Active Coping',
  'Use of Informational Support' ,
  'Positive Reframing' ,
  'Planning' ,
  'Emotional Support' ,
  'Venting' ,
  'Humor' ,
  'Acceptance' ,
  'Religion' ,
  'Self-blame' ,
  'Self-distraction' ,
  'Denial' ,
  'Substance Use',
  'Behavioral Disengagement' ,
  'Problem-Focused Coping' ,
  'Emotion-Focused Coping' ,
  'Avoidant Coping' ,
  'Problem-Focused Coping-Partial',
  'Emotion-Focused Coping-Partial',
  'Decision Making',
  'Values' ,
  'Affection',
  'Stability' ,
  'Conflict' ,
  'Activities',
  'Discussion' ,
  'Consensus',
  'Satisfaction',
  'Cohesion',
  'Physical Function',
  'Anxiety',
  'Depression',
  'Fatigue' ,
  'Sleep Disturbance' ,
  'Social Participation' ,
  'Pain Interference' ,
  'Mobility' ,
  'Activities of Daily Living' ,
  'Emotional Well Being' ,
  'Stigma' ,
  'Social Support' ,
  'Cognition' ,
  'Communication',
  'Bodily Discomfort',
  'Orientation',
                 'Delay Recall',
                 'Abstraction',
                 'Language',
                 'Attention',
                 'Naming',
                 'Visuospatial/Executive',
  'Total Score MOCA',
  'Total Score BRS' ,
  'Total Score GDS' ,
  'Total Score GAD-7' ,
  "Summary Index",
  "Mean RR  (ms):",
                     "SDNN (ms):",
                     "Mean HR (beats/min):",
                     "RMSSD (ms):",
                     "pNNxx (%):"
  )
  )
    )|>
  dplyr::select(Instrument, Dimension, `Mean Difference`, `Std.Err.`, `95% CI`, `p-value`, t, df)|>
  dplyr::arrange(Instrument, Dimension) |>
  kableExtra::kable(
    booktabs = T,
    full_width = F,
    caption = "Intervention Measures for Patients with Parkinson’s Disease"
  ) |>
  kableExtra::collapse_rows(1)|>
  kableExtra::kable_styling(font_size = 7)
```

```{r}
cpTtestTable|>
  dplyr::filter(Instrument %in% c('PROMIS', 'GD', 'GAD7','MOCA','BRS', 'RDA', 'HRV'
  )) |>
  dplyr::filter(!(Instrument == "RDA" & dimension %in% c(
    'Decision Making','Values','Affection','Stability','Conflict',
            'Activities','Discussion', 'Total Score RDAS'
  ) ))|>
  dplyr::mutate(
    Instrument = factor(Instrument, levels = c('PROMIS', 'GD', 'GAD7','MOCA','BRS', 'RDA', "HRV"
  ),
  labels = c('PROMIS-29','GDS-SF','GAD-7','MoCA', 'BRS', 'RDAS', 'HRV')),
  Dimension = factor(dimension, levels = c(
    'Active Coping',
  'Use of Informational Support' ,
  'Positive Reframing' ,
  'Planning' ,
  'Emotional Support' ,
  'Venting' ,
  'Humor' ,
  'Acceptance' ,
  'Religion' ,
  'Self-blame' ,
  'Self-distraction' ,
  'Denial' ,
  'Substance Use',
  'Behavioral Disengagement' ,
  'Problem-Focused Coping' ,
  'Emotion-Focused Coping' ,
  'Avoidant Coping' ,
  'Problem-Focused Coping-Partial',
  'Emotion-Focused Coping-Partial',
  'Decision Making',
  'Values' ,
  'Affection',
  'Stability' ,
  'Conflict' ,
  'Activities',
  'Discussion' ,
  'Consensus',
  'Satisfaction',
  'Cohesion',
  'Physical Function',
  'Anxiety',
  'Depression',
  'Fatigue' ,
  'Sleep Disturbance' ,
  'Social Participation' ,
  'Pain Interference' ,
  'Mobility' ,
  'Activities of Daily Living' ,
  'Emotional Well Being' ,
  'Stigma' ,
  'Social Support' ,
  'Cognition' ,
  'Communication',
  'Bodily Discomfort',
  'Orientation',
                 'Delay Recall',
                 'Abstraction',
                 'Language',
                 'Attention',
                 'Naming',
                 'Visuospatial/Executive',
  'Total Score MOCA',
  'Total Score BRS' ,
  'Total Score GDS' ,
  'Total Score GAD-7',
  "Mean RR  (ms):",
                     "SDNN (ms):",
                     "Mean HR (beats/min):",
                     "RMSSD (ms):",
                     "pNNxx (%):"
  )
  )
    )|>
  dplyr::select(Instrument, Dimension, `Mean Difference`, `Std.Err.`, `95% CI`, `p-value`, t, df) |>
  dplyr::arrange(Instrument, Dimension) |>
  kableExtra::kable(
    booktabs = T,
    caption = 'Intervention Measures for Care Partners of Patients with Parkinson’s Disease',
    full_width = F
  ) |>
  kableExtra::collapse_rows(1)
```


```{r}
interpret_promis |>
  dplyr::filter(Test == "Difference")|>
  dplyr::select(RecordID, Role, dimension, Test, Tscore) |>
  ggplot2::ggplot(ggplot2::aes(x = Tscore, y = dimension))+
  ggplot2::facet_wrap(~Role)+
  ggplot2::geom_boxplot()+
  ggplot2::theme_bw()+
  ggplot2::geom_vline(xintercept = 0)+
  ggplot2::labs(
    x = "Difference in T-Score from Pre-test to Post-test",
    y = '', 
    title = 'Change in PROMIS Dimension Tscores from Pre-test to Post-test')
  
```

```{r}
hrv24hr |>
  dplyr::filter(Test == "Difference")|>
  dplyr::select(RecordID, Role, dimension, Test, Value) |>
  ggplot2::ggplot(ggplot2::aes(x =Value, y = dimension, color = Role))+
  ggplot2::geom_boxplot()+
  ggplot2::theme_bw()+
  ggplot2::geom_vline(xintercept = 0)+
  ggplot2::labs(
    x = "Difference from Pre-test to Post-test",
    y = '', 
    title = 'Change in Heart Rate Variability Variables from Pre-test to Post-test')+
  ggsci::scale_color_aaas()
```

